#!/bin/bash
#
# Copyright (c) 2012 Taylor Hutt, Logic Magicians Software
#
# This program is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

set -e;
ARG_SOURCE_DIRECTORY=/tmp/generate;

# The following set of options produce 90955 source files.
ARG_SEED=1341448741;
ARG_DEPTH=5;
ARG_SOURCES=100;
ARG_SUBDIRS=20;

rm -rf ${ARG_SOURCE_DIRECTORY};
cd $(dirname ${0});
make

./generate                                      \
    --root ${ARG_SOURCE_DIRECTORY}              \
    --seed ${ARG_SEED}                          \
    --depth ${ARG_DEPTH}                        \
    --sources ${ARG_SOURCES}                    \
    --subdirs ${ARG_SUBDIRS} >/dev/null;

echo "Source file count: " $(find ${ARG_SOURCE_DIRECTORY} -name "*.c"|wc --lines)
rm *.o ./generate
