#!/bin/bash
#
# Copyright (c) 2012 Taylor Hutt, Logic Magicians Software
#
# This program is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

#  Functions & variables common to all tests.
#
program="${0}"
directory=$(dirname "${0}");
cfg="${directory}/lmsbw-test.cfg";

if [ -z "${LMSBW_TEST_BUILD_ROOT}" ] ; then
    echo "'LMSBW_TEST_BUILD_ROOT' is not set";
    exit -1;
fi;

function expect_command_failure ()
{
    if [ $? == "0" ] ; then
        echo "Previous command succeeded when it was expected to fail.";
        exit -1;
    fi;
}

function expect_command_success ()
{
    if [ $? != "0" ] ; then
        echo "Previous command failed when it was expected to succeed.";
        exit -1;
    fi;
}

function expect_error () # (test directory, expected error text...)
{
    local test_directory="${1}";
    shift;

    while [ ! -z "${1}" ] ; do
        local error="${1}";
        shift;

        if ! grep --quiet -w -e "${error}" "${test_directory}/lmsbw-build.log"; then
            echo "Expected failure, '${error}', was not found.";
            exit -1;
        fi;
    done;
}
