#!/bin/bash
#
# Copyright (c) 2012 Taylor Hutt, Logic Magicians Software
#
# This program is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

#  Functions & variables common to all scripts.
#
program="${0}"

# fatal: Echo all arguments and exit with -1 result.
#
function fatal ()
{
    for v in "${@}" ; do
        printf "fatal: ${v}\n";
    done;
    exit -1;
}

# verbosity: Echo all aruments if '${verbose}' is set
#
function verbosity ()
{
    if [ ! -z "${verbose}" ] ; then
        echo " [${MAKELEVEL}]  " $*;
    fi;
}

# warning <component> <printf format> <printf-arguments>
#
#  Formats a message, prefixed with '**** WARNING: ' which fits in the same
#  style as the build process proper.
#
function warning ()
{
    local component=${1};
    local format=${2};
    shift 2;

    printf " [${MAKELEVEL}]  **** WARNING: ${component}: ${format}\n" ${*};
}

# message <component> <printf format> <printf-arguments>
#
#  Formats a message which fits in the same style as the build process
#  proper.
#
function message ()
{
    local component=${1};
    local format=${2};
    shift 2;

    printf " [${MAKELEVEL}]  ${component}: ${format}\n" ${*};
}
